/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oorestaurants;
import java.awt.Component;
import javax.swing.JTextField;
import java.awt.TextField;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author Lenovo
 */
public class OO_Restaurants extends javax.swing.JFrame {

    /**
     * Creates new form OO_Restaurants
     */
    public OO_Restaurants() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mealPanel = new javax.swing.JPanel();
        lblTax2 = new javax.swing.JLabel();
        tfChickenWings = new javax.swing.JTextField();
        lblSubTotal2 = new javax.swing.JLabel();
        tfMushroomSoup = new javax.swing.JTextField();
        lblTotal2 = new javax.swing.JLabel();
        tfMeatBalls = new javax.swing.JTextField();
        lblTax4 = new javax.swing.JLabel();
        lblTotal5 = new javax.swing.JLabel();
        tfLimeChicken = new javax.swing.JTextField();
        lblTotal6 = new javax.swing.JLabel();
        tfMegaBurger = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        outcomeTxtField_Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outcomeTxtField = new javax.swing.JTextArea();
        DrinksPanel = new javax.swing.JPanel();
        lblTax1 = new javax.swing.JLabel();
        tfStrawberryJuice = new javax.swing.JTextField();
        lblSubTotal1 = new javax.swing.JLabel();
        tfVanillaCone = new javax.swing.JTextField();
        lblTotal1 = new javax.swing.JLabel();
        tfMilkShake = new javax.swing.JTextField();
        lblTax3 = new javax.swing.JLabel();
        lblTotal3 = new javax.swing.JLabel();
        tfMangoShake = new javax.swing.JTextField();
        lblTotal4 = new javax.swing.JLabel();
        tfMilkTea = new javax.swing.JTextField();
        allOverTotal_Panel = new javax.swing.JPanel();
        tfTax = new javax.swing.JTextField();
        tfSubTotal = new javax.swing.JTextField();
        tfTotal = new javax.swing.JTextField();
        lblSubTotal = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblTax = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        totalBtn = new javax.swing.JButton();
        receiptBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        costsPanel = new javax.swing.JPanel();
        lblTotal7 = new javax.swing.JLabel();
        lblTotal8 = new javax.swing.JLabel();
        lblTotal9 = new javax.swing.JLabel();
        tfCostOfMeal = new javax.swing.JTextField();
        tfCostOfDrinks = new javax.swing.JTextField();
        tfTotalCost = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mealPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        lblTax2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTax2.setText("Chicken Wings");

        tfChickenWings.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfChickenWings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfChickenWingsActionPerformed(evt);
            }
        });

        lblSubTotal2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSubTotal2.setText("Mushroom Soup");

        tfMushroomSoup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lblTotal2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotal2.setText("Meatballs");

        tfMeatBalls.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lblTax4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTax4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTax4.setText("Meals");

        lblTotal5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotal5.setText("Mega Burger");

        tfLimeChicken.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lblTotal6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotal6.setText("Lime Chicken");

        tfMegaBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout mealPanelLayout = new javax.swing.GroupLayout(mealPanel);
        mealPanel.setLayout(mealPanelLayout);
        mealPanelLayout.setHorizontalGroup(
            mealPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mealPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(mealPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mealPanelLayout.createSequentialGroup()
                        .addComponent(lblTotal5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfMegaBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mealPanelLayout.createSequentialGroup()
                        .addComponent(lblTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfMeatBalls, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mealPanelLayout.createSequentialGroup()
                        .addComponent(lblSubTotal2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfMushroomSoup, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mealPanelLayout.createSequentialGroup()
                        .addComponent(lblTotal6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfLimeChicken, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mealPanelLayout.createSequentialGroup()
                        .addComponent(lblTax2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfChickenWings, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(mealPanelLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(lblTax4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        mealPanelLayout.setVerticalGroup(
            mealPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mealPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTax4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mealPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfChickenWings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTax2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mealPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMushroomSoup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mealPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMeatBalls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mealPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLimeChicken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mealPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMegaBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(mealPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 460, 270));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 64)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Restaurant Management System");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 8));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\OneDrive\\Pictures\\Camera Roll\\coffee.jpg")); // NOI18N
        jLabel3.setText("jLabel2");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 8));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\OneDrive\\Pictures\\Camera Roll\\coffee.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 8));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1089, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 120));

        outcomeTxtField_Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        outcomeTxtField.setColumns(20);
        outcomeTxtField.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        outcomeTxtField.setRows(5);
        jScrollPane1.setViewportView(outcomeTxtField);

        javax.swing.GroupLayout outcomeTxtField_PanelLayout = new javax.swing.GroupLayout(outcomeTxtField_Panel);
        outcomeTxtField_Panel.setLayout(outcomeTxtField_PanelLayout);
        outcomeTxtField_PanelLayout.setHorizontalGroup(
            outcomeTxtField_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outcomeTxtField_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addContainerGap())
        );
        outcomeTxtField_PanelLayout.setVerticalGroup(
            outcomeTxtField_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outcomeTxtField_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(outcomeTxtField_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 130, 400, 560));

        DrinksPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        lblTax1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTax1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTax1.setText("Drinks");

        tfStrawberryJuice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfStrawberryJuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStrawberryJuiceActionPerformed(evt);
            }
        });

        lblSubTotal1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSubTotal1.setText("Smoothie");

        tfVanillaCone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lblTotal1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotal1.setText("Mango Shake");

        tfMilkShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lblTax3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTax3.setText("Milk Shake");

        lblTotal3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotal3.setText("Milk Tea");

        tfMangoShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lblTotal4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotal4.setText("Strawberry Juice");

        tfMilkTea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout DrinksPanelLayout = new javax.swing.GroupLayout(DrinksPanel);
        DrinksPanel.setLayout(DrinksPanelLayout);
        DrinksPanelLayout.setHorizontalGroup(
            DrinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DrinksPanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(lblTax1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(DrinksPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(DrinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DrinksPanelLayout.createSequentialGroup()
                        .addComponent(lblTotal4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                        .addComponent(tfStrawberryJuice, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DrinksPanelLayout.createSequentialGroup()
                        .addGroup(DrinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSubTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTax3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotal1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(DrinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DrinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfMilkShake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                .addComponent(tfVanillaCone, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(tfMangoShake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DrinksPanelLayout.createSequentialGroup()
                        .addComponent(lblTotal3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfMilkTea, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        DrinksPanelLayout.setVerticalGroup(
            DrinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DrinksPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTax1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addGap(200, 200, 200))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DrinksPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(DrinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTax3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DrinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfVanillaCone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubTotal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DrinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMangoShake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DrinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMilkTea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DrinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStrawberryJuice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(DrinksPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 470, 270));

        allOverTotal_Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        tfTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTaxActionPerformed(evt);
            }
        });

        tfSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        tfTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSubTotal.setText("SubTotal");

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotal.setText("Total");

        lblTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTax.setText("Tax");

        javax.swing.GroupLayout allOverTotal_PanelLayout = new javax.swing.GroupLayout(allOverTotal_Panel);
        allOverTotal_Panel.setLayout(allOverTotal_PanelLayout);
        allOverTotal_PanelLayout.setHorizontalGroup(
            allOverTotal_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, allOverTotal_PanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(allOverTotal_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(allOverTotal_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfSubTotal)
                    .addComponent(tfTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(tfTax, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(74, 74, 74))
        );
        allOverTotal_PanelLayout.setVerticalGroup(
            allOverTotal_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allOverTotal_PanelLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(allOverTotal_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(allOverTotal_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(allOverTotal_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotal)
                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        getContentPane().add(allOverTotal_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 470, 180));

        buttonPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        totalBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalBtn.setText("Total");
        totalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBtnActionPerformed(evt);
            }
        });

        receiptBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        receiptBtn.setText("Receipt");
        receiptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptBtnActionPerformed(evt);
            }
        });

        resetBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        exitBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(receiptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(exitBtn)
                        .addComponent(resetBtn))
                    .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totalBtn)
                        .addComponent(receiptBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );

        getContentPane().add(buttonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 940, 90));

        costsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        lblTotal7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotal7.setText("Cost of Meal");

        lblTotal8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotal8.setText("Cost of Drinks");

        lblTotal9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotal9.setText("Total Cost");

        tfCostOfMeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfCostOfMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCostOfMealActionPerformed(evt);
            }
        });

        tfCostOfDrinks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfCostOfDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCostOfDrinksActionPerformed(evt);
            }
        });

        tfTotalCost.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfTotalCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalCostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout costsPanelLayout = new javax.swing.GroupLayout(costsPanel);
        costsPanel.setLayout(costsPanelLayout);
        costsPanelLayout.setHorizontalGroup(
            costsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(costsPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(costsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(costsPanelLayout.createSequentialGroup()
                        .addComponent(lblTotal9)
                        .addGap(99, 99, 99)
                        .addComponent(tfTotalCost))
                    .addGroup(costsPanelLayout.createSequentialGroup()
                        .addGroup(costsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotal8)
                            .addComponent(lblTotal7))
                        .addGap(62, 62, 62)
                        .addGroup(costsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCostOfMeal)
                            .addComponent(tfCostOfDrinks, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))))
                .addGap(74, 74, 74))
        );
        costsPanelLayout.setVerticalGroup(
            costsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(costsPanelLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(costsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCostOfMeal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(costsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotal8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCostOfDrinks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(costsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        getContentPane().add(costsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 460, 180));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void receiptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptBtnActionPerformed
         
        //======================================================================//
        int refs = 1325 + (int) (Math.random()*4238);
        //======================================================================//
          
            Calendar timer = Calendar.getInstance();
            timer.getTime();
            SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
            timeFormat.format(timer.getTime());
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");
            dateFormat.format(timer.getTime());
            
            outcomeTxtField.append("\tRestaurant Management Systems:\n"+
                    "Reference:\t\t\t" + refs + 
                    "\n=====================================================\n"+
                    "Meals:\t\t" + tfCostOfMeal.getText() + "\n\n" +
                    "Drinks:\t\t" + tfCostOfDrinks.getText() + "\n\n" +
                    "Cost of items:\t" + tfTotalCost.getText() + "\n\n" +
                    "=====================================================" + "\n\n" +
                    "Tax:\t" + tfTax.getText() + "\n\n" +
                    "Subtottal:\t" + tfSubTotal.getText() + "\n\n" +
                    "Total:\t" + tfTotal.getText() + "\n" + 
                    "=====================================================" + 
                    "\nDate: " + dateFormat.format(timer.getTime()) + 
                    "\nTime: " +  timeFormat.format(timer.getTime()) +
                    "\n\n\t\tThank you and come again!");
        
    }//GEN-LAST:event_receiptBtnActionPerformed

    private void tfTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTaxActionPerformed

    private void tfStrawberryJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStrawberryJuiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStrawberryJuiceActionPerformed

    private void tfChickenWingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfChickenWingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfChickenWingsActionPerformed

    private void tfCostOfMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCostOfMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCostOfMealActionPerformed

    private void tfCostOfDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCostOfDrinksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCostOfDrinksActionPerformed

    private void tfTotalCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotalCostActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        SubClass iExit = new SubClass();
        iExit.iExitSystem();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        JTextField txtField_Empty = null;
        
            for(Component c : DrinksPanel.getComponents()){
            if(c.getClass().toString().contains("javax.swing.JTextField")){
                txtField_Empty = (JTextField)c;
                txtField_Empty.setText("0");
            }
        }
        //******************************************************************************************************************//
        for(Component c : mealPanel.getComponents()){
            if(c.getClass().toString().contains("javax.swing.JTextField")){
                txtField_Empty = (JTextField)c;
                txtField_Empty.setText("0");
            }
        }
        //********************************************************************************************************************//
        
                for(Component c : costsPanel.getComponents()){
            if(c.getClass().toString().contains("javax.swing.JTextField")){
                txtField_Empty = (JTextField)c;
                txtField_Empty.setText("0");
            }
        }
        //******************************************************************************************************************//
        for(Component c : allOverTotal_Panel.getComponents()){
            if(c.getClass().toString().contains("javax.swing.JTextField")){
                txtField_Empty = (JTextField)c;
                txtField_Empty.setText("0");
            }
        }
        //*****************************************************************************************************************//
        outcomeTxtField.setText(null);
    }//GEN-LAST:event_resetBtnActionPerformed

    private void totalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBtnActionPerformed
      SubClass itemCost = new SubClass();
      
      double item_Tax, item_SubTotal, item_Total;
      
      //Meals
      itemCost.ChickenWings = itemCost.price_ChickenWings * Double.parseDouble(tfChickenWings.getText());
         itemCost.LimeChicken = itemCost.price_LimeChicken * Double.parseDouble(tfLimeChicken.getText());
          itemCost.MushroomSoup = itemCost.price_MushroomSoup * Double.parseDouble(tfMushroomSoup.getText());
          itemCost.MeatBalls = itemCost.price_MeatBalls * Double.parseDouble(tfMeatBalls.getText());
           itemCost.MegaBurger = itemCost.price_MegaBurger* Double.parseDouble(tfMegaBurger.getText());
           
           //Drinks
           itemCost.MilkShake = itemCost.price_MilkShake* Double.parseDouble(tfMilkShake.getText());
           itemCost.Smoothie = itemCost.price_Smoothie* Double.parseDouble(tfVanillaCone.getText());
           itemCost.MangoShake = itemCost.price_MangoShake* Double.parseDouble(tfMangoShake.getText());
           itemCost.MilkTea = itemCost.price_MilkTea* Double.parseDouble(tfMilkTea.getText());
           itemCost.StrawberryJuice = itemCost.price_StrawberryJuice* Double.parseDouble(tfStrawberryJuice.getText());
           
           item_SubTotal = itemCost.getAmount();
           item_Tax = itemCost.getTax(item_SubTotal);
           item_Total = item_SubTotal + item_Tax;
           
           String SubTotal = String.format("₱%.2f",item_SubTotal);
           tfSubTotal.setText(SubTotal);
           
            String Tax = String.format("₱%.2f",item_Tax);
            tfTax.setText(Tax);
           
           String Total = String.format("₱%.2f",item_Total);
           tfTotal.setText(Total);
           
           String Meal = String.format("₱%.2f",itemCost.Meals);
           tfCostOfMeal.setText(Meal);
           
           String Drink = String.format("₱%.2f",itemCost.Drinks);
           tfCostOfDrinks.setText(Drink);
           
           String TotalCost = String.format("₱%.2f",itemCost.TotalOfMealsDrinks);
           tfTotalCost.setText(TotalCost);
    }//GEN-LAST:event_totalBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
   
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
     UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OO_Restaurants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DrinksPanel;
    private javax.swing.JPanel allOverTotal_Panel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel costsPanel;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblSubTotal1;
    private javax.swing.JLabel lblSubTotal2;
    private javax.swing.JLabel lblTax;
    private javax.swing.JLabel lblTax1;
    private javax.swing.JLabel lblTax2;
    private javax.swing.JLabel lblTax3;
    private javax.swing.JLabel lblTax4;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotal1;
    private javax.swing.JLabel lblTotal2;
    private javax.swing.JLabel lblTotal3;
    private javax.swing.JLabel lblTotal4;
    private javax.swing.JLabel lblTotal5;
    private javax.swing.JLabel lblTotal6;
    private javax.swing.JLabel lblTotal7;
    private javax.swing.JLabel lblTotal8;
    private javax.swing.JLabel lblTotal9;
    private javax.swing.JPanel mealPanel;
    private javax.swing.JTextArea outcomeTxtField;
    private javax.swing.JPanel outcomeTxtField_Panel;
    private javax.swing.JButton receiptBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JTextField tfChickenWings;
    private javax.swing.JTextField tfCostOfDrinks;
    private javax.swing.JTextField tfCostOfMeal;
    private javax.swing.JTextField tfLimeChicken;
    private javax.swing.JTextField tfMangoShake;
    private javax.swing.JTextField tfMeatBalls;
    private javax.swing.JTextField tfMegaBurger;
    private javax.swing.JTextField tfMilkShake;
    private javax.swing.JTextField tfMilkTea;
    private javax.swing.JTextField tfMushroomSoup;
    private javax.swing.JTextField tfStrawberryJuice;
    private javax.swing.JTextField tfSubTotal;
    private javax.swing.JTextField tfTax;
    private javax.swing.JTextField tfTotal;
    private javax.swing.JTextField tfTotalCost;
    private javax.swing.JTextField tfVanillaCone;
    private javax.swing.JButton totalBtn;
    // End of variables declaration//GEN-END:variables
}
